/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.locadoraveiculodesktop.telas;

import br.com.locadoraveiculodesktop.classes.Fabricante;
import br.com.locadoraveiculodesktop.recurso.FabricanteRecurso;
import br.com.locadoraveiculodesktop.util.RespostaServidor;
import br.com.locadoraveiculodesktop.util.TableCellRendererColor;
import com.google.gson.Gson;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michel A. Medeiros
 */
public class FabricanteTela extends javax.swing.JInternalFrame {

    JMenuItem FabricanteMenu;
    int editar = 0;

    Long codigo;
    String fabricanteNome;

    int linha = 0;
    int coluna = 0;

    List<Fabricante> listaFabricante = new ArrayList<>();

    public FabricanteTela(JMenuItem FabricanteMenu) {
        initComponents();
        JTable_Fabricante.setDefaultRenderer(Object.class, new TableCellRendererColor());
        
        this.FabricanteMenu = FabricanteMenu;
        JL_Mensagem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTF_Fabricante = new javax.swing.JTextField();
        JB_Salvar = new javax.swing.JButton();
        JL_Mensagem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_Fabricante = new javax.swing.JTable();
        JB_Pesquisar = new javax.swing.JButton();
        JTF_Pesquisar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fabricante");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fabricante: ");

        JB_Salvar.setText("Salvar");
        JB_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SalvarActionPerformed(evt);
            }
        });

        JL_Mensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JL_Mensagem.setForeground(new java.awt.Color(255, 0, 0));
        JL_Mensagem.setText("Mensagens do sistema");

        JTable_Fabricante.setBackground(new java.awt.Color(255, 255, 255));
        JTable_Fabricante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JTable_Fabricante.setForeground(new java.awt.Color(255, 255, 255));
        JTable_Fabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fabricante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable_Fabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_FabricanteMouseClicked(evt);
            }
        });
        JTable_Fabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTable_FabricanteKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(JTable_Fabricante);

        JB_Pesquisar.setText("Pesquisar");
        JB_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTF_Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Salvar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_Pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTF_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JL_Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JL_Mensagem)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Salvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Pesquisar)
                    .addComponent(JTF_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        FabricanteMenu.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosed

    private void JB_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SalvarActionPerformed
        try {
            Fabricante fabricante = new Fabricante();
            fabricante.setNome(JTF_Fabricante.getText());
            if (editar == 1) {
                fabricante.setCodigo(codigo);
            }

            //código que faz o trabalho ;-) cria o JSON
            Gson gson = new Gson();
            String json = gson.toJson(fabricante);

            FabricanteRecurso fr = new FabricanteRecurso();
            String urlPart = "fabricante/inserirFabricante";
            int resposta = fr.salvar(json, urlPart);

            RespostaServidor rs = new RespostaServidor();
            String mensagem = rs.retornarResposta(resposta);

            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText(mensagem);

            JTF_Fabricante.setText("");

            if (editar == 1) {
                editar = 0;
                JB_PesquisarActionPerformed(null);
            }

        } catch (Exception e) {
            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JB_SalvarActionPerformed

    private void JB_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_PesquisarActionPerformed
        try {
            FabricanteRecurso fr = new FabricanteRecurso();
            String palavra = JTF_Pesquisar.getText();

            if (palavra.equals("")) {
                String urlPart = "fabricante/todos";
                listaFabricante = fr.pesquisar(urlPart);
            } else {
                String urlPart = "fabricante/todos/" + palavra;
                listaFabricante = fr.pesquisar(urlPart);
            }

            atualizar_tabela();

        } catch (Exception e) {
            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JB_PesquisarActionPerformed

    private void JTable_FabricanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTable_FabricanteKeyPressed
        try {

            int code = evt.getKeyCode();
            if (code == KeyEvent.VK_DELETE) {
                Object[] options = {"Sim", "Não"};
                int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir este registro", "Atenção!!!",
                        JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                if (opcao == JOptionPane.YES_OPTION) {
                    FabricanteRecurso fr = new FabricanteRecurso();
                    Long id = codigo;
                    String urlPart = "fabricante/remove/" + id;
                    int resposta = fr.excluir(urlPart);

                    RespostaServidor rs = new RespostaServidor();
                    String mensagem = rs.retornarResposta(resposta);

                    System.out.println("mensagem " + mensagem);

                    JTF_Fabricante.setText("");

                    JB_PesquisarActionPerformed(null);
                }
            } else if (linha + 1 == listaFabricante.size()) {
                if (code == KeyEvent.VK_UP) {
                    linha--;
                    usando_setas();
                } else if (code == KeyEvent.VK_DOWN) {
                    JL_Mensagem.setVisible(true);
                    JL_Mensagem.setText("Fim da lista.");
                } else {
                    linha = 0;
                    usando_setas();
                }

            } else {
                if ((code == KeyEvent.VK_DOWN || code == KeyEvent.VK_ENTER)) {

                    if (listaFabricante.size() - 1 > linha) {
                        linha++;
                        usando_setas();
                    }

                } else if (code == KeyEvent.VK_UP && linha > 0) {
                    linha--;
                    usando_setas();
                }
            }

        } catch (Exception e) {
            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JTable_FabricanteKeyPressed

    private void JTable_FabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_FabricanteMouseClicked
        try {
            editar = 1;
            linha = JTable_Fabricante.getSelectedRow();
            coluna = JTable_Fabricante.getSelectedColumn();
            JTable_Fabricante.editCellAt(linha, coluna);

            codigo = (Long) JTable_Fabricante.getValueAt(linha, 0);
            fabricanteNome = (String) JTable_Fabricante.getValueAt(linha, 1);

            JTF_Fabricante.setText(fabricanteNome);

            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Pressione a tecla delete do teclado para excluir um registro");

            System.out.println("linha mouse clicou " + linha);

        } catch (Exception e) {
            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_JTable_FabricanteMouseClicked

    private void atualizar_tabela() {
        try {
            JTable_Fabricante.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JTable_Fabricante.getColumnModel().getColumn(0).setPreferredWidth(100);
            JTable_Fabricante.getColumnModel().getColumn(1).setPreferredWidth(400);

            DefaultTableModel modelo = (DefaultTableModel) JTable_Fabricante.getModel();
            modelo.setRowCount(0);

            if (listaFabricante.isEmpty()) {
                JL_Mensagem.setVisible(true);
                JL_Mensagem.setText("Nenhum resultado encontrado.");
            } else {
                listaFabricante.stream().forEach((_item) -> {
                    modelo.addRow(new Object[]{
                        _item.getCodigo(), _item.getNome()
                    });
                });
            }

        } catch (Exception e) {
            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Erro: " + e.getMessage());
        }
    }

    public void usando_setas() {
        try {

            // System.out.println("linha us " + linha);
            codigo = (Long) JTable_Fabricante.getValueAt(linha, 0);
            fabricanteNome = (String) JTable_Fabricante.getValueAt(linha, 1);

            JTF_Fabricante.setText(fabricanteNome);

            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Você está em " + fabricanteNome);

        } catch (Exception e) {
            JL_Mensagem.setVisible(true);
            JL_Mensagem.setText("Erro: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Pesquisar;
    private javax.swing.JButton JB_Salvar;
    private javax.swing.JLabel JL_Mensagem;
    private javax.swing.JTextField JTF_Fabricante;
    private javax.swing.JTextField JTF_Pesquisar;
    private javax.swing.JTable JTable_Fabricante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
